### PR TITLE
Fix TypeError: multiInput is not a function

### LINKED ISSUE #61: TypeError: multiInput is not a function
With rollup@3.3.0 I get the following error:

```
[!] TypeError: multiInput is not a function
```

Config file looks like this...

```
// rollup.config.mjs

import commonjs from "@rollup/plugin-commonjs";
import json from "@rollup/plugin-json";
import resolve from "@rollup/plugin-node-resolve";
import { createRequire } from "node:module";
import multiInput from "rollup-plugin-multi-input";
import peerDepsExternal from "rollup-plugin-peer-deps-external";
import postcss from "rollup-plugin-postcss";
import typescript from "rollup-plugin-typescript2";

const require = createRequire(import.meta.url);
const packageJson = require("./package.json");

export default {
  input: ["src/**/*.js"],
  external: [...Object.keys(packageJson.dependencies)],
  output: [
    {
      dir: "lib/cjs/",
      format: "cjs",
    },
    {
      dir: "lib/esm/",
      format: "esm",
    },
  ],
  plugins: [
    peerDepsExternal(),
    resolve({ browser: true }),
    commonjs(),
    typescript({
      useTsconfigDeclarationDir: true,
      tsconfig: "./tsconfig.build.json",
    }),
    postcss({
      extensions: [".css"],
    }),
    json(),
    multiInput(),
  ],
};

```

### PR DESCRIPTION
**Pull request by ayan4m1**
Closes #61

### CODE REVIEW

**Comment by alfredosalzillo** [comment]
@ayan4m1 As stated in the nodejs documentation at [https://nodejs.org/api/packages.html](https://nodejs.org/api/packages.html)

> The .mjs and .cjs extensions can be used to mix types within the same package:
>
>Within a "type": "module" package, Node.js can be instructed to interpret a particular file as [CommonJS](https://nodejs.org/api/modules.html) by naming it with a .cjs extension (since both .js and .mjs files are treated as ES modules within a "module" package).
>
>Within a "type": "commonjs" package, Node.js can be instructed to interpret a particular file as an [ES module](https://nodejs.org/api/esm.html) by naming it with an .mjs extension (since both .js and .cjs files are treated as CommonJS within a "commonjs" package).

To avoid breaking other projects using this library is better to set `"type": "commonjs"` and should work as expected, forcing your version to treat the .js files as cjs files

**Comment by ayan4m1** [comment]
Sorry, are you saying I should change type to commonjs and rename plugin.js to plugin.mjs?

**Comment by alfredosalzillo** [comment]
@ayan4m1 only change the type to commonjs to force newer node version to read it as a commonjs node file

**Comment by ayan4m1** [comment]
OK, that's what the PR currently contains.

**Review by alfredosalzillo — COMMENTED** [review]
ok

**Review by alfredosalzillo — APPROVED** [review]

**Comment by ayan4m1** [comment]
Didn't fix the issue, I still need to use `multiInput.default()` in all my projects that are relying on this plugin.

**Comment by alfredosalzillo** [comment]
@ayan4m1 can you post the configuration of your project?
Ex. Node version, rollup version

**Pull request merged**
